### PR TITLE
Format source using clang-format

### PR DESCRIPTION
**Pull request by rnestler**
The source was in a very uncommon style for C/C++ programmers.  This is
the output of clang-format without any arguments.

### CODE REVIEW

**Comment by fmorgner** [comment]
Even though the style might be uncommon, it is well known in the C++ community by its name ["Whitesmiths"](https://en.wikipedia.org/wiki/Indent_style#Whitesmiths_style). I guess clang-format defaults to LLVM-style, which has a lot of Java-ish things to it.

I don't consider style changes to be of any value **unless** there is a project standard style guide and the changes make the code conform to it. Additionally, I don't want to engage in style discussions since code formatting is irrelevant. There exist numerous tools to format code, with clang-format being one of the worst despite the potential it could have had due to it being based on the llvm/clang infrastructure, and everybody can clone the code and use their own formatter to view and edit it. When committing, the code should be in the formatting of the original author so as not to generate "useless" changes.

Sorry.

**Comment by dbrgn** [comment]
While I also find the style strange, I agree with @fmorgner that the first author can decide on a style to use, as long as there is no de-facto standard like PEP8 or rustfmt.

**Comment by rnestler** [comment]
> Even though the style might be uncommon, it is well known in the C++ community by its name ["Whitesmiths"](https://en.wikipedia.org/wiki/Indent_style#Whitesmiths_style).

I _knew_ I have seen the style elsewhere before, must have been this Wikipedia page :smiley:.

>  I guess clang-format defaults to LLVM-style, which has a lot of Java-ish things to it.

Yes it defaults to LLVM-style. I'm not sure what you mean by Java-ish things, for me it looks just like [K&R](https://en.wikipedia.org/wiki/Indent_style#K.26R_style) style.

> Additionally, I don't want to engage in style discussions since code formatting is irrelevant.

Agree.

> There exist numerous tools to format code, with clang-format being one of the worst despite the potential it could have had due to it being based on the llvm/clang infrastructure.

Why is clang-format one of the worst? It worked fine for me.

Do you now a tool which formats in "Whitesmiths" style? Because I couldn't really get my editor to work with this style and manually adjusting everything isn't that much fun :cry:

>  unless there is a project standard style guide and the changes make the code conform to it.
> ...
> as long as there is no de-facto standard like PEP8 or rustfmt.

For what it's worth, there is an [Arduino style guide](https://www.arduino.cc/en/Reference/StyleGuide) which may be helpful, since this is an Arduino project. But it's a bit scarce on the formatting side.

> Sorry.

No need to apologize :wink:

**Comment by rnestler** [comment]
> Do you now a tool which formats in "Whitesmiths" style? Because I couldn't really get my editor to work with this style and manually adjusting everything isn't that much fun :cry:

Found one! http://astyle.sourceforge.net/astyle.html `astyle --style=whitesmith --indent=spaces=2` leaves the file as is.

**Pull request closed without merging**
